title: iAcisclo Dev
subtitle: My Portfolio
description: ''
url: ''
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Contact
    url: /contact
author_logo: profile.png
author: Ignacio Acisclo
author_bio: 'Hi, my name is Ignacio Acisclo.'
author_email: iacisclo@gmail.com
author_location: Spain
author_website_url: 'https://github.com/iAcisclo'
typewrite-text: I am passionate iOS developer from Spain
hero_cover_img: sample_cover.jpg
author_work_experiences:
  - company_name: Autentia
    company_logo: google.png
    company_url: 'https://autentia.com'
    designation: Software Engineer
    description: Worked on various iOS Products
    visibility: true
author_education_details: []
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
twitter_username: iacisclo
github_username: iacisclo
facebook_username: Ignacio Acisclo
linkedin_username: Ignacio Acisclo
formspree_email: iacisclo@gmail.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
