title: iAcisclo Dev
subtitle: My Portfolio
description: ''
url: ''
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
author_logo: profile.png
author: Ignacio Acisclo
author_bio: >-
  Hi, my name is Ignacio Acisclo, I have been developing iOS applications since
  2011 by vocation and since 2013 professionally.

  I am passionate about technology and science, I practice insect breeding as a
  hobby and I exercise every day.

  I think I'm lucky to work on something that doesn't bore me any day of the
  year.
author_email: iacisclo@gmail.com
author_location: Spain
author_website_url: 'https://github.com/iAcisclo'
typewrite-text: I am passionate iOS developer from Spain
hero_cover_img: sample_cover.jpg
author_work_experiences:
  - company_name: Autentia
    company_logo: autentia.jpeg
    company_url: 'https://autentia.com'
    designation: Software Engineer
    description: Working on multiple iOS projects
    visibility: true
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: 'https://gamershub.in'
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: 'https://hack4r.com'
    visibility: true
twitter_username: iacisclo
github_username: iacisclo
linkedin_username: Ignacio Acisclo
formspree_email: iacisclo@gmail.com
olvy_organization: devlopr
olvy_widget_type: sidebar
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: 'false'
show_author_project_details: 'false'
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin
jekyll_admin:
  homepage: posts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
